from .group_beautiful.group_beautiful import Group_Beautiful
from .group_grammer.group_grammer import Group_Grammer
from .group_psi.group_psi import Group_Psi
from .group_ssl.group_ssl import Group_SSL
from .group_whois.group_whois import Group_Whois
from .group_textstat.group_textstat import Group_Texstat
from .group_automation.group_automation import Group_Automation
from .group_automation_2.group_automation_2 import Group_Automation_2
from .group_beautiful_2.group_beautiful_2 import Group_Beautiful_2
from .group_img.group_img import Group_Img
from .group_accessibility.group_accessibility import Group_Accessibility
from .group_seo.group_seo import Group_SEO
from .group_psi_2.group_psi_2 import Group_Psi_2
from .group_vulnerability.group_vulnerability import Group_Vulnerability